name: Qt mingw64 build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build_release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Fetch dependencies and build Qt
        shell: cmd
        run: call run.bat release

      - name: Upload Qt
        uses: actions/upload-artifact@v3.1.3
        with:
          name: qt_release_mingw64.tar.gz
          path: qt_release_mingw64.tar.gz
          
  build_arm64:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Fetch dependencies and build Qt
        shell: cmd
        run: |
          set CI_ANDROID_ABI=arm64-v8a
          call run.bat release

      - name: Upload Qt
        uses: actions/upload-artifact@v3.1.3
        with:
          name: qt_release_mingw64_arm64-v8a.tar.gz
          path: qt_release_mingw64.tar.gz
          
  build_armeabi:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Fetch dependencies and build Qt
        shell: cmd
        run: |
          set CI_ANDROID_ABI=armeabi-v7a
          call run.bat release

      - name: Upload Qt
        uses: actions/upload-artifact@v3.1.3
        with:
          name: qt_release_mingw64_armeabi-v7a.tar.gz
          path: qt_release_mingw64.tar.gz
          
  build_x86_64:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Fetch dependencies and build Qt
        shell: cmd
        run: |
          set CI_ANDROID_ABI=x86_64
          call run.bat release

      - name: Upload Qt
        uses: actions/upload-artifact@v3.1.3
        with:
          name: qt_release_mingw64_x86_64.tar.gz
          path: qt_release_mingw64.tar.gz
          
  build_x86:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Fetch dependencies and build Qt
        shell: cmd
        run: |
          set CI_ANDROID_ABI=x86
          call run.bat release

      - name: Upload Qt
        uses: actions/upload-artifact@v3.1.3
        with:
          name: qt_release_mingw64_x86.tar.gz
          path: qt_release_mingw64.tar.gz

      # - name: Upload Qt+Docs
      #   uses: actions/upload-artifact@v3.1.3
      #   with:
      #     name: qt_release_mingw64_with_docs.tar.gz
      #     path: qt_release_mingw64_with_docs.tar.gz

          
  # build_debug:
  #   runs-on: windows-latest

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Fetch dependencies and build Qt
  #       shell: cmd
  #       run: call run.bat debug

  #     - name: Upload Qt
  #       uses: actions/upload-artifact@v3.1.3
  #       with:
  #         name: qt_debug_mingw64.tar.gz
  #         path: qt_debug_mingw64.tar.gz

      # - name: Upload Qt+Docs
      #   uses: actions/upload-artifact@v3.1.3
      #   with:
      #     name: qt_release_mingw64_with_docs.tar.gz
      #     path: qt_release_mingw64_with_docs.tar.gz
  build_release_lnx:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Fetch dependencies and build Qt
        shell: bash
        run: |
          export START_DIR=`pwd`
          curl -o "alpine.tar.gz" "https://github.com/FetheredSerpent/qt-mingw64/releases/download/dependencies/alpine-minirootfs-3.19.1-x86_64.tar.gz"
          curl -L -o qt-everywhere-src-6.5.2.tar.xz https://github.com/FetheredSerpent/qt-mingw64/releases/download/dependencies/qt-everywhere-src-6.5.2.tar.xz
          mkdir work
          tar -xf qt-everywhere-src-6.5.2.tar.xz -C work
          tar -xzf alpine.tar.gz -C /tmp/alpine
          
          rm -rf qt-everywhere-src-6.5.2.tar.xz
          rm -rf alpine.tar.gz
          
          mkdir -p /tmp/alpine/work
          mount --bind $START_DIR/work /tmp/alpine/work
          mount --bind /dev /tmp/alpine/dev
          mount --bind /proc /tmp/alpine/proc
          mount --bind /sys /tmp/alpine/sys
          cp scripts/build_lnx.sh /tmp/alpine
          SHELL=/bin/sh PATH=$PATH:/bin:/sbin chroot /tmp/alpine sh /build_lnx.sh

      - name: Upload Qt
        uses: actions/upload-artifact@v3.1.3
        with:
          name: qt_release_lnx.tar.gz
          path: qt_release_lnx.tar.gz
