name: Qt mingw64 build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build_release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Fetch dependencies and build Qt
        shell: cmd
        run: call run.bat release

      - name: Upload Qt
        uses: actions/upload-artifact@v3.1.3
        with:
          name: qt_release_mingw64.tar.gz
          path: qt_release_mingw64.tar.gz

      # - name: Upload Qt+Docs
      #   uses: actions/upload-artifact@v3.1.3
      #   with:
      #     name: qt_release_mingw64_with_docs.tar.gz
      #     path: qt_release_mingw64_with_docs.tar.gz

          
  # build_debug:
  #   runs-on: windows-latest

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Fetch dependencies and build Qt
  #       shell: cmd
  #       run: call run.bat debug

  #     - name: Upload Qt
  #       uses: actions/upload-artifact@v3.1.3
  #       with:
  #         name: qt_debug_mingw64.tar.gz
  #         path: qt_debug_mingw64.tar.gz

      # - name: Upload Qt+Docs
      #   uses: actions/upload-artifact@v3.1.3
      #   with:
      #     name: qt_release_mingw64_with_docs.tar.gz
      #     path: qt_release_mingw64_with_docs.tar.gz
